{
 "title": "Tailscale",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"tailscale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Advertised Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tailscaled_advertised_routes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Approved Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tailscaled_approved_routes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health Messages",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_health_messages{type=\"warning\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Bound Traffic [Mbps]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "# kbps\r\n# rate(tailscaled_inbound_bytes_total{path=\"direct_ipv4\"}[$__rate_interval]) * 8 / 1000\r\n# Mbps\r\nrate(tailscaled_inbound_bytes_total{path=\"direct_ipv4\"}[$__rate_interval]) * 8 / 1000000",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "# kbps\r\n# rate(tailscaled_inbound_packets_total{path=\"derp\"}[$__rate_interval]) * 8 / 1000\r\n# Mbps\r\nrate(tailscaled_inbound_packets_total{path=\"derp\"}[$__rate_interval]) * 8 / 1000000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Out-Bound Traffic [Mbps]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "# rate(tailscaled_outbound_bytes_total{path=\"direct_ipv4\"}[$__rate_interval]) * 8 / 1000\r\nrate(tailscaled_outbound_bytes_total{path=\"direct_ipv4\"}[$__rate_interval]) * 8 / 1000000",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "# rate(tailscaled_outbound_bytes_total{path=\"derp\"}[$__rate_interval]) * 8 / 1000\r\nrate(tailscaled_outbound_bytes_total{path=\"derp\"}[$__rate_interval]) * 8 / 1000000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "In-Bound Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_packets_total{path=\"direct_ipv4\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "rate(tailscaled_inbound_packets_total{path=\"derp\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Out-Bound Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(tailscaled_outbound_packets_total{path=\"direct_ipv4\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "rate(tailscaled_outbound_packets_total{path=\"derp\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "In-Bound Packets Dropped by reason",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_dropped_packets_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Out-Bound Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(tailscaled_outbound_dropped_packets_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}