global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "tailscale"
    static_configs:
      - targets:
          - "100.100.100.100"
        labels:
          service: "tailscale"

  - job_name: "traefik"
    static_configs:
      - targets:
          - "traefik:8080"
        labels:
          service: "traefik"
    metrics_path: /metrics
    scheme: http

  - job_name: immich_api
    static_configs:
      - targets:
          - "immich-server:8081"

  - job_name: immich_microservices
    static_configs:
      - targets:
          - "immich-server:8082"
